### PR TITLE
Update to docfx 2.71.1

### PR DESCRIPTION
**Pull request by Arhell**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@SeanKilleen please take a look when you have time.

**Comment by SeanKilleen** [comment]
@Arhell this looks like a minor release that doesn't have compelling features for us to warrant updating right now. Am I missing something?

**Comment by Arhell** [comment]
> @Arhell this looks like a minor release that doesn't have compelling features for us to warrant updating right now. Am I missing something?

No, I just keep the latest version

**Comment by SeanKilleen** [comment]
Sorry @Arhell  -- closing this so that I could accept an external contribution. I appreciate you putting it out there!

**Pull request closed without merging**
