### PR TITLE
Update to docfx 2.62.1

### PR DESCRIPTION
**Pull request by Arhell**
https://github.com/dotnet/docfx/releases/tag/v2.62.1

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@SeanKilleen cc

**Comment by SeanKilleen** [comment]
@Arhell is this a critical fix for you, or are you just keeping a routine lookout?

**Comment by Arhell** [comment]
no, of course, just updating as much as possible, making a small contribution

**Comment by SeanKilleen** [comment]
Totally fine (and appreciated!) Just wanted to make sure it wasn't crucial since you tagged me. 👍

**Review by SeanKilleen — APPROVED** [review]
Thank you for this! ❤️

**Pull request merged**
